service: chaos-dashboard-bff
provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    -  Effect: Allow
       Action:
         - 'lambda:InvokeFunction'
       Resource: '*'

custom:
  chaosService: chaos-service

package:
  exclude:
    - .git/**
    - node_modules/**
    - test/**
    - '*'
    - 'src/.node_version'
    - 'src/package.json'
    - 'src/yarn.lock'
  include:
    - 'src/**'

functions:
  graphql:
    handler: src/graphql.handler
    memorySize: 512
    timeout: 10
    environment:
      COUNT_LAMBDA: ${self:custom.chaosService}-${opt:stage}-instanceCount
      LIST_LAMBDA: ${self:custom.chaosService}-${opt:stage}-instanceList
    events:
        - http:
            path: graphql
            method: post
            cors: true
